name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  NEXT_PUBLIC_CHAIN_ID: uni-3
  NEXT_PUBLIC_CHAIN_NAME: NEXT_PUBLIC_CHAIN_NAME
  NEXT_PUBLIC_CHAIN_BECH32_PREFIX: NEXT_PUBLIC_CHAIN_BECH32_PREFIX
  NEXT_PUBLIC_CHAIN_RPC_ENDPOINT: NEXT_PUBLIC_CHAIN_RPC_ENDPOINT
  NEXT_PUBLIC_CHAIN_REST_ENDPOINT: NEXT_PUBLIC_CHAIN_REST_ENDPOINT
  NEXT_PUBLIC_FEE_DENOM: NEXT_PUBLIC_FEE_DENOM
  NEXT_PUBLIC_STAKING_DENOM: NEXT_PUBLIC_STAKING_DENOM
  NEXT_PUBLIC_SITE_URL: NEXT_PUBLIC_SITE_URL
  NEXT_PUBLIC_CW20_CODE_ID: 1
  NEXT_PUBLIC_DAO_ADDRESS: NEXT_PUBLIC_DAO_ADDRESS
  NEXT_PUBLIC_SEARCH_URL: NEXT_PUBLIC_SEARCH_URL
  NEXT_PUBLIC_SEARCH_API_KEY: NEXT_PUBLIC_SEARCH_API_KEY
jobs:
  ci:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn build
